In [1]:
import numpy as np

In [2]:
# http://www.scipy-lectures.org/intro/numpy/array_object.html

In [2]:
simple_array_1d = np.array([1,2,3,4,5,6])

In [3]:
simple_array_1d

array([1, 2, 3, 4, 5, 6])

In [4]:
type(simple_array_1d)

numpy.ndarray

In [5]:
simple_array_1d.ndim

1

In [6]:
simple_array_1d.shape

(6,)

Why it is useful: Memory-efficient container that provides fast numerical operations.

In [7]:
l = range(1000)
%timeit [i**2 for i in l]

279 µs ± 5.28 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
np_l = np.arange(1000)
%timeit np_l**2

1.26 µs ± 2.86 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Interactive help:

In [10]:
np.array?

Looking for something:

In [11]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [16]:
np.con*?
# like a wildcard search

### 1.3.1.2. Creating arrays

1-D

In [21]:
a = np.array(range(10))

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a.ndim

1

In [24]:
a.shape

(10,)

In [25]:
len(a)

10

2-D, 3-D ....

In [27]:
b = np.array([[1,2,3],[4,5,6]]) # 2 X 3 array ie 2 rows and 3 columns

In [28]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b.ndim

2

In [30]:
b.shape

(2, 3)

In [33]:
len(b) # returns the size of the first dimension

2

In [34]:
c= np.array([[[1],[2]],[[3],[4]]])

In [35]:
c.ndim

3

In [36]:
c.shape

(2, 2, 1)

In [37]:
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [38]:
len(c)

2

Create a simple two dimensional array. First, redo the examples from above. And then create your own: how about odd numbers counting backwards on the first row, and even numbers on the second?

In [46]:
a = np.array([np.arange(9,0,-2),np.arange(10,0,-2)])

In [47]:
a

array([[ 9,  7,  5,  3,  1],
       [10,  8,  6,  4,  2]])

In [48]:
a.ndim

2

### Functions for creating arrays

Evenly spaced:

In [49]:
evenly_spaced = np.arange(10)

In [50]:
evenly_spaced

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
start_end_step = np.arange(1, 9 , 2) # end is excluded

In [52]:
start_end_step

array([1, 3, 5, 7])

or by number of points:

In [53]:
start_end_numOfPoints = np.linspace(0,1,6) # 6 is number of points

In [55]:
start_end_numOfPoints # included start and endpoinots as well in the array

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [59]:
d = np.linspace(0,1,6, endpoint=False) # not inclding endpoints

In [57]:
d

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333])

In [60]:
np.linspace?

In [61]:
d = np.linspace(0,1,6, endpoint=False, retstep=True) # not inclding endpoints

In [64]:
d

(array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
        0.83333333]), 0.16666666666666666)

note above we got a __tuple__ where first one is the array 
and __second values__ in the tuple is __size of spacing__ between the values

In [63]:
np.linspace?

Common arrays:

In [69]:
a = np.ones((3,3))

In [71]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
a.ndim

2

In [73]:
a = np.ones(2)

In [74]:
a

array([1., 1.])

In [75]:
a.ndim

1

In [76]:
b = np.zeros((3,3))

In [77]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
c = np.eye(3) # identity

In [79]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
diagonal = np.diag(np.array([1,2,3,4,5]))

In [81]:
diagonal

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [83]:
daigg2 = np.diag(np.linspace(0,2,num=10, endpoint=False))

In [84]:
daigg2

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.4, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.6, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.8, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 1.2, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 1.4, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1.6, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1.8]])

np.random: random numbers (Mersenne Twister PRNG):

Uniform between 0 to 1 

In [85]:
a = np.random.rand(4)

uniform in [0, 1]

In [86]:
a

array([0.50755507, 0.0211933 , 0.43352176, 0.44631306])

In [94]:
aa = np.random.rand(10)

In [95]:
aa

array([0.76807887, 0.30289844, 0.01517509, 0.46336869, 0.70333708,
       0.06604089, 0.66901142, 0.34547906, 0.59172147, 0.22905346])

In [96]:
b = np.random.randn(4)

In [97]:
b

array([ 0.23361135, -0.12545121, -0.28385152,  0.26110561])

For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu

###### used for normal distribution (Gaussian) 

In [99]:
emp = np.empty(2)

In [100]:
emp

array([1., 1.])

In [102]:
emp = np.empty((2,3))

In [104]:
emp

array([[0.        , 0.16666667, 0.33333333],
       [0.5       , 0.66666667, 0.83333333]])

In [105]:
emp = np.empty([2,3])

In [106]:
emp

array([[0.        , 0.16666667, 0.33333333],
       [0.5       , 0.66666667, 0.83333333]])

## 1.3.1.3. Basic data types